In [1]:
#Write a Python program to print the following string in a specific format (see the output). #Write a Python program to print the following string in a specific format (see the output). 
print 'Twinkle, twinkle, little star'
print '            How I wonder what you are'


SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Twinkle, twinkle, little star')? (<ipython-input-1-372bad77182e>, line 2)

In [2]:
#Write a Python program to get the Python version you are using. 
import sys 
print ('Python version')
print (sys.version)
print (sys.version_info)

Python version
3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]
sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)


In [3]:
#curreant datr and time
import datetime
now = datetime.datetime.now()
print(now.strftime('%Y-%m-%d'))
print(now.strftime('%H:%M:%S'))

2019-08-17
15:41:43


In [5]:
#rite a Python program which accepts the radius of a circle from the user and compute the area

print('radius of the circle')
r = input()
o = 3.14 * (r ^ 2)
print (' the output',o)


radius of the circle
1


TypeError: unsupported operand type(s) for ^: 'str' and 'int'

In [ ]:
from math import pi
print('radius of the circle')
r = input()
o = pi* (r * r)
print (' the output',o)

In [ ]:
print input('1st name:') 

print input('last name:')

In [ ]:
fname = input("Input your First Name : ")
lname = input("Input your Last Name : ")
print ("Hello  " + lname + " " + fname)

In [ ]:
#Write a Python program which accepts a sequence of comma-separated numbers from user and generate a list and a tuple with those numbers.

print 'no'
no = input ()
print 'the sqeunce:',no




In [6]:
#Write a Python program which accepts a sequence of comma-separated numbers from user and generate a list and a tuple with those numbers.

print 'no'
no = input ("inpu:  )
a= no.split(",")
print 'the sqeunce:',a


SyntaxError: Missing parentheses in call to 'print'. Did you mean print('no')? (<ipython-input-6-c9b60ce3db50>, line 3)

In [ ]:
values = input("Input some comma seprated numbers : ")
list = values.split(",")
tuple = tuple(list)
print('List : ',list)
print('Tuple : ',tuple)

In [ ]:
from math import pi
r = float(input ("Input the radius of the circle : "))
print ("The area of the circle with radius " + str(r) + " is: " + str(pi * r**2))

In [ ]:
from math import pi
r = float(input('the area is : '))
print('the output', str(r)+ str(pi * r**2))

In [7]:
first = input('first name')
last  = input ('last name')
print ('last name', "" , last, first)

first nameankit
last namenahdfebe
last name  nahdfebe ankit


In [9]:
#Python int(x, base=10):

# Python3 program to get input from user 
  
# accepting integer from the user 

no = int(input('the int:'))
no1 = int( "%s" % no)
no2 = int( "%s%s" % (no, no))
no3 = int( "%s%s%s" % (no,no,no))
print (no1+no2+no3)

the int:3
369


In [ ]:
import calendar
 
y =int(input(": "))
m = int(input(": "))
print (calendar.month(y,m))


In [ ]:
from datetime import date
f_date = date(2019, 7, 1)
l_date = date(2019, 7, 21)
delta = l_date - f_date
 
print(delta.days)


In [ ]:
from  math import pi
r = float(input("the volume of sph:"))
v =4/3 * pi *r **3
print("the area is", v)
      

In [ ]:
no = int(input())
if (no >400):
    print(' no is ok')
elif (no >600):
    print ( 'no is good')
else:
    print ("all is good")

In [ ]:
n = int(input())
if (n %2 ==0):
    print ('it is even', n)
else:
    print('it is odd')

In [ ]:
n = int(input())
if (n %2 ==0):
    print ('it is even', n)
else:
    print('it is odd')

In [ ]:
##User is prompted to enter a guess. If the user guesses wrong then the prompt appears again until the guess is correct, on successful guess, user will get a "Well guessed!" message, and the program will exit.

import random
tar, guess= random.randint(1,10),0
while tar != guess:
    guess=int(input('guess the no from 1 to 10:'))
print ('guess')

In [ ]:
s =9
s


In [11]:
l = [1,2,3,4,5,6]
l2 = []
for index, i in enumerate(l):
    if i ==10:
        break
    if i < 10:
        continue
    l2.append((index, i*i))
else:
    print('out of loop')
l2

out of loop


[]

In [10]:
lst1 = [4, 7, 13, 11, 3, 11, 15]
lst2 = []

for index, e in enumerate(lst1):
    if e == 10:
        break
    if e < 10:
        continue
    lst2.append((index, e*e))
else:
    print("out of loop without using break statement")

lst2

out of loop without using break statement


[(2, 169), (3, 121), (5, 121), (6, 225)]

In [ ]:
import sys; x = 'foo'; sys.stdout.write(x + '\n')


In [ ]:
x= 0
while x <10:
    print('x is currently: ', x, end ="")
    
    print('adding to one')
    x+1
    

In [ ]:
##list Comprehension


ls = ['ankit', 'sanket', 'mom ', 'dad']
hello= ['hello  ' + ls for ls in ls]
print(hello)


In [ ]:
no = [55,6,6,454,6,4,6,4,6,8,25,8,3]
even =[num for num in no if num %2 ==0]
print (even)

In [ ]:
no = [55,6,6,454,6,4,6,4,6,8,25,8,3]
even =[num for num in no if num ==0]
print (even)

In [ ]:
n  = 12
for i in range (n):
    for j in range (i):
        print ('# _#', end = '')
    print ('')

In [ ]:
for i in range (n ,0, -2):
    for j in range (i):
        print('*', end ='')
    print ('')

In [ ]:
hum_age = int(input('input of dog age in years: '))
if hum_age < 0:
    print( 'its a positive age')
    exit() 
elif hum_age <=2:
    d_age = hum_age *10.5
else:
    d_age =21 +(hum_age -2)*4
print ('age of dog ',d_age)

In [ ]:
vo= str(input('given input: '))
if vo in ('a','e','i','o','u'):
    print('its vovals' )
else:
     print('its consonant')

### Python Exercise: Sum of two given integers. However, if the sum is between 15 to 20 it will return 20

In [ ]:
def sum(x,y):
    sum = x+y
    if sum in range(15,20):
        return 20
    else:
        return sum
print(sum(10,12))

####   Write a Python program to check a triangle is equilateral, isosceles or scalene. Go to the editor
Note :
An equilateral triangle is a triangle in which all three sides are equal.
A scalene triangle is a triangle that has three unequal sides.
An isosceles triangle is a triangle with (at least) two equal sides.

In [ ]:
triangle = int(input("the angle in degree :"))
x= int(input('x: '))
y= int(input('y: '))
z= int(input('z: '))
if x== y== z:
    print('equilatreal triangle')
elif x==y or x==z or y==z:
    print('iso triangle ')
else:
    print('scalene triangle')

In [ ]:
#xample of isinstance() function
num = 100
# true because num is an integer
print(isinstance(num, int))

# false because num is not a float
print(isinstance(num, float))

# false because num is not a complex number
print(isinstance(num, complex))

In [ ]:

#the no of odd and even counts
l = range(1,100)
#l= (1,2,3,4,5,6,7,8,9,65,66,46,8,46,6,9,46,466,5)
odd  = 0

even = 0
for x in  l:
    if not x %2 :
        even +=1
    else:
        odd+=1
    
print ('the even :',even)
print('the odd:', odd)

##  Write a Python program that prints each item and its corresponding type from the following list.
Write a Python program that prints each item and its corresponding type from the following list.

Sample List : datalist = [1452, 11.23, 1+2j, True, 'w3resource', (0, -1), [5, 12], {"class":'V', "section":'A'}]

In [ ]:
#Write a Python program that prints each item and its corresponding type from the following list.

#Sample List : datalist = [1452, 11.23, 1+2j, True, 'w3resource', (0, -1), [5, 12], {"class":'V', "section":'A'}]


d= [646,44,3,60.5,46,3,1+6j,49674,98,'abchnoc',(0,-5,6),[8,6], {'class':'v', 'secton':'A'}]
for item in d:
    print ('type of ', item, 'is', type(item))

## Write a Python program to get the Fibonacci series between 0 to 50.

Note : The Fibonacci Sequence is the series of numbers :
0, 1, 1, 2, 3, 5, 8, 13, 21, ....https://www.w3resource.com/w3r_images/python-conditional-image-exercise-9.png


In [ ]:
x,y=0,1
while y<50:
    print(y)
    x,y = y,x+ y

In [ ]:
for i in range (1,10):
    print (i, i**2)

In [ ]:
l = [0,1,2,3,45]
for i in range (len(l)):
    j=1/2
    if j -int(j) == 0.0:
        l[i] = l[i]+1
    else: l[i] =i**2
l

In [ ]:
def double_the_number(num=1):
    return num * 2

print(double_the_number())

### With the for loop we can execute a set of statements, once for each item in a list, tuple, set etc.



In [ ]:
lo= ['anlkit', 'sanketw', 'mom', 'dad']
for z in lo:
    print (z)

##  evenfor loop does not require an indexing variable to set beforehand.

In [ ]:
for z in 'ankit':
    print (lo)
    

The break Statement
With the break statement we can stop the loop before it has looped through all the items:# 

In [ ]:
l= ['anlkit', 'daada','sanketw', 'mom', 'dad' ]
for x in l:
    print(x)
    if x =='daada':
        break
    

### Exit the loop when x is "banana", but this time the break comes before the print


In [ ]:
l= ['anlkit', 'daada','sanketw', 'mom', 'dad' ]
for x in l:
    print(x)
    if x =='daada':
        break
    print (x)

### The continue Statement
With the continue statement we can stop the current iteration of the loop, and continue with the next:#### 

In [ ]:
l

In [ ]:
l
for a in l:
    if a == 'sanketw':
        continue
    print(a)

The range() Function

To loop through a set of code a specified number of times, we can use the range() function,
The range() function returns a sequence of numbers, starting from 0 by default, and increments by 1 (by default), and ends at a specified number.### 

In [ ]:
for x in range (10):
    print (x)

## The range() function defaults to 0 as a starting value, however it is possible to specify the starting value by adding a parameter: range(2, 6), which means values from 2 to 6 (but not including 6):

In [ ]:
for z in range (1,6):
    print(z)

## the range() function defaults to increment the sequence by 1, however it is possible to specify the increment value by adding a third parameter: range(2, 30, 3):


In [ ]:
for s in range(1,6,3):
    print(s)

### Else in For Loop
The else keyword in a for loop specifies a block of code to be executed when the loop is finished:## 

In [ ]:
for i in range(8):
    print(i)
else:
    print('stop')

## Nested Loops
A nested loop is a loop inside a loop.

The "inner loop" will be executed one time for each iteration of the "outer loop":

In [ ]:
a = ['gaurab','brina','suka']
a
b= ['shillong', 'ghy', 'tezpur']
for x in a:
    for y in b:
        print (x,y)
        break

##  for variable in sequence:  
   # body_of_loop that has set of statements
   # which requires repeated execution 

In [ ]:
a2= [1,23,4,5,6,8,5,3,2,2]

sq = 0
for val in a2:
    sq= val*val
    print(sq)

In [ ]:
# Program to print squares of all numbers present in a list

# List of integer numbers
numbers = [1, 2, 4, 6, 11, 20]

# variable to store the square of each num temporary
sq = 0

# iterating over the given list
for val in numbers:
    # calculating square of each number
    sq = val * val
    # displaying the squares
    print(sq)

In [ ]:
sum = 0
for val in range(1,10):
    sum = sum+1
print(sum)

In [ ]:
for num in range(4):
    for num1 in range (3):
        print(num , num1)
        break

In [ ]:
i = 5
j= 8
while i < 10:
    while j <12:
        print(i,",",j)
        j= j+1
        i = i+1

In [ ]:
a2

In [ ]:
a2 =[1, 23, 4, 5, 6, 8, 5, 3, 2, 2]
for num in a2:
    if num%2==0:
        continue
    print(num)

In [ ]:
for num in [20, 11, 9, 66, 4, 89, 44]:
    # Skipping the iteration when number is even
    if num%2 == 0:
        continue
    # This statement will be skipped for all even numbers
    print(num)

## Creating a Function
In Python a function is defined using the def keyword:### 

In [ ]:
def my_function():
    print('hello from a function')
my_function()

### Calling a Function
To call a function, use the function name followed by parenthesis:


## Parameters
Information can be passed to functions as parameter.

Parameters are specified after the function name, inside the parentheses. You can add as many parameters as you want, just separate them with a comma.

The following example has a function with one parameter (fname). When the function is called, we pass along a first name, which is used inside the function to print the full name 

In [ ]:
def my_fun(name):
    print(name+' ankit')
my_fun('nagdeve')
my_fun('sanket')

In [ ]:
def fun(city):
    print(city+    '  Nagpur')
fun('ankit')
fun('sanket')
fun('anita')
fun('naresh')

###  Passing a List as a Parameter
You can send any data types of parameter to a function (string, number, list, dictionary etc.), and it will be treated as the same data type inside the function.

E.g. if you send a List as a parameter, it will still be a List when it reaches the function:

In [ ]:
food =['app','bana','pomo']
def fun(food):
    for x in food:
        print (x)
fun(food)

In [ ]:
def fun(f):
    return 5**f
    
print(fun(2))
print(fun(5))
        

###  Recursion
Python also accepts function recursion, which means a defined function can call itself.

Recursion is a common mathematical and programming concept. It means that a function calls itself. This has the benefit of meaning that you can loop through data to reach a result.

The developer should be very careful with recursion as it can be quite easy to slip into writing a function which never terminates, or one that uses excess amounts of memory or processor power. However, when written correctly recursion can be a very efficient and mathematically-elegant approach to programming.

In this example, tri_recursion() is a function that we have defined to call itself ("recurse"). We use the k variable as the data, which decrements (-1) every time we recurse. The recursion ends when the condition is not greater than 0 (i.e. when it is 0).

To a new developer it can take some time to work out how exactly this works, best way ###  

In [13]:
class cir (object):
    pi =3.14
    
    def __init__(self, radius=1):
        self.radius= radius
    
    def area(self):
        return self.radius *2 * cir.pi
    
    def setradius(self, radius):
        self.radius = radius
    
    def getradius(self):
        return self.radius

c=cir()
c.setradius(2)
c.getradius()
c.area()
        
        
        
        
    

12.56

In [18]:
import numpy as np


In [19]:
list = [1,23,45,6,78,9,9,8]
a= np.array(list)

array([ 1, 23, 45,  6, 78,  9,  9,  8])

In [32]:
listo= [[1,2,3],[3,3,5],[5,6,7],[2,3,4]]
ab = np.array(listo)
ab

array([[1, 2, 3],
       [3, 3, 5],
       [5, 6, 7],
       [2, 3, 4]])

In [34]:

print(ab.shape)

(4, 3)


In [41]:
a= np.arange(1,10)
a



In [43]:
b= np.arange(11,20)
b

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [42]:
c=np.arange(21,30)
c

array([21, 22, 23, 24, 25, 26, 27, 28, 29])

In [50]:
s= print(a,b,c)
p =np.array(s)    

[1 2 3 4 5 6 7 8 9] [11 12 13 14 15 16 17 18 19] [21 22 23 24 25 26 27 28 29]


In [51]:
print (p.shape)

()


In [59]:
np.zeros((2, 5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### eye
Creates an identity matrix of given size. Identity matrix is one in which all the diagonal elements are 1s. Rest all of the elemnts are zeros

In [61]:
np.eye(1)

array([[1.]])

## linspace
Linspace: Return evenly spaced numbers over a specified interval.

linspace(start, stop, num=50, endpoint=True, retstep=False)

Will return num number of values
Equally spaced samples in the closed interval [start, stop] or the half-open interval [start, stop)
Closed or half-open interval depends on whether 'endpoint' is True or False.### 

In [70]:
np.linspace(0 , 100, 9)

array([  0. ,  12.5,  25. ,  37.5,  50. ,  62.5,  75. ,  87.5, 100. ])

### How do I generate Random Numbers?¶

Numpy also has lots of ways to create random number arrays of given shape

rand:

numpy.random.rand(d0, d1, …, dn) Create an array of the given shape and populate it with random samples from a uniform distribution

randn:

numpy.random.randn(d0, d1, …, dn)creates an array of specified shape and fills it with random values as per standard normal distribution.

If positive arguments are provided, randn generates an array of shape (d0, d1, …, dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 (if any of the d_i are floats, they are first converted to integers by truncation).

A single float randomly sampled from the distribution is returned if no argument is provided.

randint:

Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low, high). If high is None (the default), then results are from [0, low).

In [76]:
# random number (uniform distribution) array of shape (3 , 4)

np.random.rand(2,3)

array([[0.11564908, 0.41899306, 0.46427666],
       [0.71474198, 0.33872986, 0.07406491]])

In [81]:
# random number (standard normal distribution) array of shape (2, 3)
np.random.randn(2,2)

array([[0.74243513, 0.53198487],
       [0.16468761, 0.26633802]])

In [85]:
# 10 random integers between 4 (inclusive) to 40 (exclusive)

np.random.randint(4, 40, 10)


array([21, 33, 13,  4, 29,  4,  5, 24, 36, 19])

In [92]:
# 10 random integers upto 50 (exclusive). This makes the start value default to 0.
# The size parameter dictates the return array shape


np.random.randint(50, size = (9,3))

array([[11, 36, 13],
       [45, 46, 37],
       [19,  8,  7],
       [11,  9, 23],
       [16, 15, 32],
       [10, 18, 47],
       [23, 29, 49],
       [28, 38,  7],
       [ 9, 24,  7]])

In [129]:
import csv
import urllib
import pandas as pd
import os


In [159]:
f = pd.read_csv("/home/ankit/Documents/sangeet/weather_small_2012.csv")
f


Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0     2012-01-01 00:00:00      -1.8                -3.9           86   
1     2012-01-01 01:00:00      -1.8                -3.7           87   
2     2012-01-01 02:00:00      -1.8                -3.4           89   
3     2012-01-01 03:00:00      -1.5                -3.2           88   
4     2012-01-01 04:00:00      -1.5                -3.3           88   
5     2012-01-01 05:00:00      -1.4                -3.3           87   
6     2012-01-01 06:00:00      -1.5                -3.1           89   
7     2012-01-01 07:00:00      -1.4                -3.6           85   
8     2012-01-01 08:00:00      -1.4                -3.6           85   
9     2012-01-01 09:00:00      -1.3                -3.1           88   
10    2012-01-01 10:00:00      -1.0                -2.3           91   
11    2012-01-01 11:00:00      -0.5                -2.1           89   
12    2012-01-01 12:00:00      -0.2                -2.0           88   
13    2012-01-01 13:00:00       0.2                -1.7           87   
14    2012-01-01 14:00:00       0.8                -1.1           87   
15    2012-01-01 15:00:00       1.8                -0.4           85   
16    2012-01-01 16:00:00       2.6                -0.2           82   
17    2012-01-01 17:00:00       3.0                 0.0           81   
18    2012-01-01 18:00:00       3.8                 1.0           82   
19    2012-01-01 19:00:00       3.1                 1.3           88   
20    2012-01-01 20:00:00       3.2                 1.3           87   
21    2012-01-01 21:00:00       4.0                 1.7           85   
22    2012-01-01 22:00:00       4.4                 1.9           84   
23    2012-01-01 23:00:00       5.3                 2.0           79   
24    2012-01-02 00:00:00       5.2                 1.5           77   
25    2012-01-02 01:00:00       4.6                 0.0           72   
26    2012-01-02 02:00:00       3.9                -0.9           71   
27    2012-01-02 03:00:00       3.7                -1.5           69   
28    2012-01-02 04:00:00       2.9                -2.3           69   
29    2012-01-02 05:00:00       2.6                -2.3           70   
...                   ...       ...                 ...          ...   
8754  2012-12-30 18:00:00     -12.6               -16.0           76   
8755  2012-12-30 19:00:00     -13.4               -16.5           77   
8756  2012-12-30 20:00:00     -13.8               -16.5           80   
8757  2012-12-30 21:00:00     -13.8               -16.5           80   
8758  2012-12-30 22:00:00     -13.7               -16.3           81   
8759  2012-12-30 23:00:00     -12.1               -15.1           78   
8760  2012-12-31 00:00:00     -11.1               -14.4           77   
8761  2012-12-31 01:00:00     -10.7               -14.0           77   
8762  2012-12-31 02:00:00     -10.1               -13.4           77   
8763  2012-12-31 03:00:00     -11.8               -14.4           81   
8764  2012-12-31 04:00:00     -10.5               -12.8           83   
8765  2012-12-31 05:00:00     -10.2               -12.4           84   
8766  2012-12-31 06:00:00      -9.7               -11.7           85   
8767  2012-12-31 07:00:00      -9.3               -11.3           85   
8768  2012-12-31 08:00:00      -8.6               -10.3           87   
8769  2012-12-31 09:00:00      -8.1                -9.6           89   
8770  2012-12-31 10:00:00      -7.4                -8.9           89   
8771  2012-12-31 11:00:00      -6.7                -7.9           91   
8772  2012-12-31 12:00:00      -5.8                -7.5           88   
8773  2012-12-31 13:00:00      -4.6                -6.6           86   
8774  2012-12-31 14:00:00      -3.4                -5.7           84   
8775  2012-12-31 15:00:00      -2.3                -4.6           84   
8776  2012-12-31 16:00:00      -1.4                -4.0           82   
8777  2012-12-31 17:00:00      -1.1                -3.3 

In [161]:
tem = f['Temp (C)'].astype(np.float16)


In [164]:
dp= f['Dew Point Temp (C)'].astype(np.float16)


In [166]:
far= (tem *9/5)+32
far

0       28.765625
1       28.765625
2       28.765625
3       29.296875
4       29.296875
5       29.484375
6       29.296875
7       29.484375
8       29.484375
9       29.656250
10      30.203125
11      31.093750
12      31.640625
13      32.375000
14      33.437500
15      35.250000
16      36.687500
17      37.406250
18      38.843750
19      37.562500
20      37.750000
21      39.187500
22      39.906250
23      41.562500
24      41.375000
25      40.281250
26      39.031250
27      38.656250
28      37.218750
29      36.687500
          ...    
8754     9.312500
8755     7.890625
8756     7.156250
8757     7.156250
8758     7.343750
8759    10.218750
8760    12.015625
8761    12.734375
8762    13.812500
8763    10.765625
8764    13.093750
8765    13.640625
8766    14.531250
8767    15.265625
8768    16.515625
8769    17.406250
8770    18.687500
8771    19.937500
8772    21.562500
8773    23.718750
8774    25.875000
8775    27.859375
8776    29.484375
8777    30.015625
8778    29

In [167]:
print(tem + dp)

0       -5.699219
1       -5.500000
2       -5.199219
3       -4.699219
4       -4.800781
5       -4.703125
6       -4.601562
7       -5.000000
8       -5.000000
9       -4.398438
10      -3.300781
11      -2.599609
12      -2.199219
13      -1.500000
14      -0.299805
15       1.400391
16       2.400391
17       3.000000
18       4.800781
19       4.398438
20       4.500000
21       5.699219
22       6.296875
23       7.300781
24       6.699219
25       4.601562
26       3.000000
27       2.199219
28       0.599609
29       0.298828
          ...    
8754   -28.593750
8755   -29.906250
8756   -30.296875
8757   -30.296875
8758   -30.000000
8759   -27.203125
8760   -25.500000
8761   -24.703125
8762   -23.500000
8763   -26.187500
8764   -23.296875
8765   -22.593750
8766   -21.406250
8767   -20.593750
8768   -18.906250
8769   -17.703125
8770   -16.296875
8771   -14.593750
8772   -13.296875
8773   -11.203125
8774    -9.101562
8775    -6.902344
8776    -5.398438
8777    -4.398438
8778    -4

In [168]:
print(tem +100)

0        98.1875
1        98.1875
2        98.1875
3        98.5000
4        98.5000
5        98.6250
6        98.5000
7        98.6250
8        98.6250
9        98.6875
10       99.0000
11       99.5000
12       99.8125
13      100.1875
14      100.8125
15      101.8125
16      102.6250
17      103.0000
18      103.8125
19      103.1250
20      103.1875
21      104.0000
22      104.3750
23      105.3125
24      105.1875
25      104.6250
26      103.8750
27      103.6875
28      102.8750
29      102.6250
          ...   
8754     87.3750
8755     86.6250
8756     86.1875
8757     86.1875
8758     86.3125
8759     87.8750
8760     88.8750
8761     89.3125
8762     89.8750
8763     88.1875
8764     89.5000
8765     89.8125
8766     90.3125
8767     90.6875
8768     91.3750
8769     91.8750
8770     92.6250
8771     93.3125
8772     94.1875
8773     95.3750
8774     96.6250
8775     97.6875
8776     98.6250
8777     98.8750
8778     98.6875
8779    100.1250
8780    100.1875
8781     99.50

In [165]:
array1 = np.arange(1, 10, dtype=np.float16).reshape(3, 3)
array2 = np.arange(100, 109, dtype=np.float16).reshape(3, 3)

print(array1)
print(array2)


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[100. 101. 102.]
 [103. 104. 105.]
 [106. 107. 108.]]
